//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DevelopmentCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tests
    {
        public int Id { get; set; }
        public int IdStudent { get; set; }
        public int MinScore { get; set; }
        public int MaxScore { get; set; }
        public System.DateTime DateCheck { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
